site_name: CloudVelum
site_description: CloudVelum is an AWS Cloudwatch monitoring framework that accelerates your ability to get up and running with native AWS monitoring services.
site_url: https://cloudvelum.1strategy.com/
theme:
  language: en
  name: material
  palette:
    scheme: default
    # scheme: preference
  font:
    text: Inter
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/logo-white.png
  favicon: assets/logo.png
# repo_name: 1strategy/cloudvelum
# repo_url: https://github.com/1Strategy/vpc-starter-template
edit_uri: ''
plugins:
  - search
nav:
  - ğŸ  Home: index.md
  - ğŸ‘©â€ğŸ« Tutorial:
    - tutorial/index.md
  - â˜ï¸ Services:
    - services/index.md
    - Compute:
      - services/compute/autoscaling.md
      - services/compute/ec2.md
      - services/compute/ecs.md
      - services/compute/elasticbeanstalk.md
      - services/compute/statemachine.md
    - Storage:
      - services/storage/rds.md
    - Networking:
      - services/networking/apigateway.md
  - ğŸš¨ Alarms: alarms.md
  - ğŸ· Tags: tags.md
  - ğŸ§ƒ Examples: examples.md
  # - ğŸ™‹â€ FAQ: faq.md
  # - ğŸ“Š Dashboards:
  #   - dashboards/index.md
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - attr_list
  - meta
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
  - icon: fontawesome/brands/gitlab
    link: https://gitlab.com/1strategy/cloudvelum
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/1strategy/
  - icon: fontawesome/solid/globe
    link: https://cloudvelum.1strategy.com
extra_css:
  - css/custom.css